// AOC 2023 DAY 1

const input =
    "1six7396484\n" +
    "1ninehgqtjprgnpkchxdkctzk\n" +
    "sevenmpsmstdfivebtnjljnlnpjrkhhsninefour9\n" +
    "pppmfmnfourtworxrqrfhbgx8vvxgrjzhvqmztltwo\n" +
    "9eightctkdnnllnine\n" +
    "1eight3shhj8hrglbhxsixvhntf\n" +
    "4rlqzthlhkxvzhcm6\n" +
    "bklcbpdlfctwofivesqvpxjjzlvn35zhlljrfqf\n" +
    "36qv\n" +
    "76six66nine\n" +
    "rvzrcjzjfour3seven16six\n" +
    "2eightjlm\n" +
    "eightxfcmkqjqxzxjvrfive3\n" +
    "gxonefivejnvqbgnrjxv87gnlqqfdm\n" +
    "sixphvtnrgdvthreeseven21seven4\n" +
    "sixttxkjggfourtwo13khgfcbtsq9nbbztfs\n" +
    "m8t\n" +
    "9fourfsrdbvptwos53\n" +
    "vfqjtpmtp69five\n" +
    "tb17\n" +
    "bctthnksix4onegmgpjbbxqqrmk5hnfvzcnsgh\n" +
    "2sixthreeonenine5ndxdjgkb\n" +
    "sixtfk2qjpq\n" +
    "twohccqqrfour1zjlqq\n" +
    "3nine6\n" +
    "2zrstwopsmjmzdff\n" +
    "89three\n" +
    "dnrnmhkxp45onepttcbtwosevenone1\n" +
    "tztph43five4\n" +
    "nine4threerrllzdnsprvninezkf\n" +
    "brsnjcr8nineseven3four9\n" +
    "7sixsevennine5t1five8\n" +
    "twobhxqznqcft7nhfgcxqfourthree8\n" +
    "7sixbdbvdnckqslvxh8\n" +
    "5cnsvq82fiveeightttmnvcm\n" +
    "kptwone34seven5\n" +
    "fourzx1\n" +
    "twodcpmrxmrgkeightsix228rmcqf\n" +
    "two9dcfjcjz2seveneight7\n" +
    "7twoqthpjdxc8xhfznninethreesix\n" +
    "vjbxtseven82vxbzjdsththreeeightg\n" +
    "524one\n" +
    "dxjqvhgtfpmtxjmlt7eight5eight\n" +
    "3mczqpssixsixx7ninenine\n" +
    "8667\n" +
    "3eight9sgbtdrrhr6lfxbmfthree\n" +
    "two1one8sixdzxqqzlnhfpkdjxseventhree\n" +
    "kmflhtjsnq1six94\n" +
    "lnrphbmqseveneightk2nine\n" +
    "s5\n" +
    "hckfhhqbsg3srnzdvm2nine\n" +
    "three58six7sixl\n" +
    "1sixfour717\n" +
    "4fivenblhmbxfjtwofive\n" +
    "jhmxb1crbttv47\n" +
    "zcfive7onecgbfqtsgpxzfbtbrnine\n" +
    "nine73mrvdntwozbvninethreemsbcbjcp\n" +
    "qclgtqkmnh8four\n" +
    "twoqmzhp6v91fiveprs\n" +
    "bjnctmcctpzdq27six93five\n" +
    "djmdzpbfzsix1eightone5plbfrone\n" +
    "btcfdlmvrnhqgvmtmn4foureightt3\n" +
    "7djtfour78\n" +
    "onetjmpgdjqlnz5two\n" +
    "one5four\n" +
    "5eight27nmlfiverlzjxpts\n" +
    "365mvfhqfhflhtzktwo\n" +
    "two8gqzcgjxtcgxvnlvfx6lvvkbq36\n" +
    "4srgn95vnqtwo9kfcchklpfvzzkcq\n" +
    "pcgjfvqlgp1663sixeight\n" +
    "pxknxlhdjs7rsjkbpzhtvzd\n" +
    "6one36eightfcqzktwotwombxr\n" +
    "3fmmdlktwoeight\n" +
    "foureightone5cgvdv\n" +
    "one9fourlsdfmbsvnxhhl\n" +
    "twosixkpcrtnhhbb3eight9six\n" +
    "3ninemrntwozvrs5tpbnz\n" +
    "sixsix3fourgrcjqsk51t\n" +
    "71six74threebrdkpfbmjnvpbbm\n" +
    "5sixbptk6ngj\n" +
    "scgttmjzqp6\n" +
    "335eight\n" +
    "one287976\n" +
    "5zgzsgeightfourkkcjl\n" +
    "47one1one\n" +
    "7one6fivesixfive\n" +
    "6ktjhbvrtsthreesixfxmtgrvtcntljrbxrxrdpcjcftwoseven\n" +
    "gltwone32vmxmzsqqfhbppvslb2\n" +
    "tfphzkcxh3twofour9oneightg\n" +
    "gdsrbtslnbsixxdfrdz45\n" +
    "3sevensevenfoureight4jnine\n" +
    "six5eightthreeseventwolf7\n" +
    "spnv4six\n" +
    "nrlrqp7qgch5cmbhgrvbtppkmt8\n" +
    "61four261bxmxxrz\n" +
    "onetwo6nbvgttmkx\n" +
    "5twofour281qhsc8\n" +
    "seven8one\n" +
    "onexsfivetwo93\n" +
    "ckrllvdxkgmjkqfpthreefrqjshlplgeightjvxhb3fourkds\n" +
    "nnzbmh3\n" +
    "ps55seventhreetwo\n" +
    "eightsix67three\n" +
    "2threehcdfdxlkcsixlsgkkqgt\n" +
    "3rjxsxfdqeight81hpr8gppmxrj\n" +
    "9skrxzdvkzzthree4rsfrgpqlonefour\n" +
    "27three8\n" +
    "pxpslqbbqmzcklvbd4\n" +
    "eightseventwo6\n" +
    "nine9dbbcqfhfkrvjb9\n" +
    "72seven\n" +
    "2twopztmbkbttdglrtv8two\n" +
    "seven87fourtbdxjzktd4sevennine\n" +
    "5qpcvmkr5ninefour\n" +
    "twotwoeightqnjjcdqq45\n" +
    "2bkccvkmeighttgqjjthreefour\n" +
    "56oneninethreevv4chvlfljbrthree\n" +
    "9sixseven9zspvdsqxzf\n" +
    "4four8ndqjtgllktwo4\n" +
    "jchmqgp85\n" +
    "dznstvthreeeightjzcxzsqbtsixqr8\n" +
    "85ntwonexlm\n" +
    "qtgfhskvonexrg13four879\n" +
    "86onetwonejf\n" +
    "ztwonexqpckxcz4jpqgthreebjmzxfnvz38nine\n" +
    "one1onekptcbbh5four\n" +
    "dnqcckvxngpndvmm7eight5seven8three\n" +
    "4nine8dgsqjhvl\n" +
    "142rgdnx\n" +
    "mprgxckmzbzvkdsgdjzfive5fivenrsxvhvs\n" +
    "five41fiveqxm12\n" +
    "sixdhgs6dtnplsix\n" +
    "seven5djeightlrnghlkvjkclmsmlgn92\n" +
    "ggtdbkngcp8\n" +
    "one58foursevenbqbbkzbf\n" +
    "nine6fourrmpbsixthreeeight52\n" +
    "twofjbhnfthreefivesix31\n" +
    "fiveeightsevenfive1fourfive\n" +
    "prhfhbpzrzghj94six6fivethree\n" +
    "3mffjmjmtfczjhjqnine\n" +
    "sktx9threesevenlxmfkkmseven45\n" +
    "13jlmhmcnvjzqsnthreeqdslgdlqzlmxgbmvzlsix3\n" +
    "four7sixktndfcxzvmxx7ninefour\n" +
    "three2nine\n" +
    "7fivezvlklbd\n" +
    "fourfivesrczxj8one\n" +
    "63five4vhklbtqmninemhsfsx5five\n" +
    "3five2six1\n" +
    "5qsfmsbtxcrvmvhn3sixthree\n" +
    "nine5xvhzlfjpbcc4xdkkps5\n" +
    "p2\n" +
    "4tczsttvpsql9seven\n" +
    "x36six83bkjhrsghkvvgtthqtt\n" +
    "8sixfive6\n" +
    "three9fivekmr\n" +
    "sixone1sixthree1\n" +
    "4reightfivetvjbsnql8\n" +
    "five3gtmgqjnkrq5\n" +
    "jtwodpjqxgthreekrxggbhgbtone1\n" +
    "fivefive4\n" +
    "gxlchjn67\n" +
    "qrlv27skhkmmninesevenqxppzdgeight\n" +
    "72five4\n" +
    "ptjtgsghgrbffgnl27one36\n" +
    "sjkdqnqkpqcpp9\n" +
    "xnggjgg1\n" +
    "onemlzp1\n" +
    "gcr74bjtddqvqktl\n" +
    "seven5bgvsknbsdmjqptkfdfour\n" +
    "twotwo9429b\n" +
    "seven5threec\n" +
    "four6mchmrqv\n" +
    "kjj1zbfsnmmcgzn\n" +
    "2twozmzfcxprsxtnrxqtkpknhmbckdqd25\n" +
    "fivefour33kzcxdhn84pphrnf2\n" +
    "mvcsbvvg4eight84one\n" +
    "eight8sixfm4sixeight\n" +
    "bvrl21\n" +
    "klnhdcppjninefivenhdk7\n" +
    "four5three19jkjc5threeone\n" +
    "jvc9cptctvcrlqsm6rkbvvknbkdpffj7\n" +
    "threesevengblssstwodzkbv1six\n" +
    "rdzmsdnbvtwogthshznninerthree34\n" +
    "onejrpznrfft83prbgzczt\n" +
    "fiveonelgjvvhbbdlx42\n" +
    "fvpjgrtwo7gbqtsslbnptbt\n" +
    "7one1\n" +
    "h4ninevlhftscfkl\n" +
    "rzrgg7qjfrrxgzctq\n" +
    "fivefmpmdb1\n" +
    "eightthreepmbzqcqthree7\n" +
    "sixldscsmfive3\n" +
    "ninefgztvvqchq8eight\n" +
    "pjtfive8zd12twonine\n" +
    "rdgmgqv2ttz\n" +
    "cgtxczthree5\n" +
    "5veighttwofour1\n" +
    "sixjninethreervzgnqqqfive6fqzntfsix\n" +
    "mfzhfivefhsksgjcst5\n" +
    "fzeight4\n" +
    "6sixeight3\n" +
    "nineqnjvxf1one4\n" +
    "hcxxcxd2seventwosevenxcjmjvmhnv\n" +
    "4four7\n" +
    "35ninezvfqsixqt2kc\n" +
    "dzloneight3\n" +
    "two7jbnkvxpnhq\n" +
    "tmljsvlcstwo37six5eighteightgtv\n" +
    "five2sevenqbponejsixvvxkc\n" +
    "9pmlrcsstwo295\n" +
    "ntbjfpzzslgpnn5fivethreefive5\n" +
    "72tlfdnjdltstwo8\n" +
    "qvzclcpqzgfkkcb93\n" +
    "three6three1xdkn\n" +
    "dgkbxqzjthree7\n" +
    "threesbjninevdvlhhq572vszh\n" +
    "six2three5\n" +
    "sixnine9xpmqlbpd\n" +
    "jvrdcf8\n" +
    "6kpcztn1\n" +
    "1jbgcthree3eight28lmfhzn\n" +
    "threetwoeightseven6\n" +
    "dnmtn8knzjjpmzfxvlrq\n" +
    "3nine5\n" +
    "19two\n" +
    "fbllsixseven1onegqpzqeight7drgf\n" +
    "szrkhpxm3hbcdgrrtg17cr2five\n" +
    "one2onehhplgxctmv1237\n" +
    "81two4zgltbz\n" +
    "one5c\n" +
    "five4sevenfourtwonvnldmvpeightfive\n" +
    "greightfive82seven\n" +
    "6four9eight747three\n" +
    "lrzgd28lzfljk68sixhnnljtkzkp2\n" +
    "vone6sixvzzzkmm24zzjskvzv\n" +
    "6seven2\n" +
    "cm16one\n" +
    "6mqxpzlxhone\n" +
    "2teightseventhreefgksfourfoursix\n" +
    "3vtqlzddlrbpxmnjqntwo7fiveseven4four\n" +
    "32ftslmt1ninejtdxnine1\n" +
    "one3sixfour4gxkchbrjzf\n" +
    "6eight9threetwo6onexcqlqfzfive\n" +
    "onefivexnjnfc1nineflckgjzsix\n" +
    "59ninefoursixfour\n" +
    "7tqjdninelnfthreekcdxfqzcl9kmvjfvbrm\n" +
    "xjbseventhree86eightlpfseven\n" +
    "cbzvgxfkgneightfive98\n" +
    "srsdrninevpzgrhrqtjfour7htbhbjttb4\n" +
    "hdmxvkcjdjninebzvmsgsseventhreemhggmhgg11\n" +
    "four32ninesmjgblfcfmvlffjtwo\n" +
    "kdx7pd3pcvrsjkczqeighttwo6\n" +
    "one2pghjsggtlbxslmthreeqgcskttvrfseven8\n" +
    "gcglgbqbxzjrpxjzvseven88\n" +
    "eight1fourpglqv\n" +
    "1twoddkk2fourseven4\n" +
    "ninejrqsksqhtl9ptd5\n" +
    "ppkeightwo5ggthreet\n" +
    "7onefhccblsv\n" +
    "eighteightmp6fqrfnpqjvx\n" +
    "bstdjfjmxjjpz12d\n" +
    "mdjmpqvhjzk616threefourplr\n" +
    "7seveneightsix\n" +
    "nhsrvtwo37ninesix\n" +
    "1one6gxkknfmc2oneightq\n" +
    "8dfflfour36\n" +
    "37d7fmzkzztwo1\n" +
    "6lmg2qmcsix7r\n" +
    "seven889xt93\n" +
    "phbhqftdvvkssxktgnc6xdcdxlxzfneight5\n" +
    "2s593xvlrdmjcz93\n" +
    "rsmgvm4\n" +
    "eightgmgqb1\n" +
    "35qfqdkdtgrvhdqdeightmqjlvlpfvzjrj\n" +
    "748\n" +
    "kbmpxqnk61ncthhtrkpznbxzfbpninehmhlbkdjtjxtx\n" +
    "foursix4mpfoureight1\n" +
    "6fzffnqzqb8tsccfour8\n" +
    "gzsxrjkcm44fournqzpseven\n" +
    "1243\n" +
    "2threeonefourtwofour\n" +
    "ninefhnr649ngld\n" +
    "fiveseven8\n" +
    "ttwo5three5ninefxsqxvkhzxzrsr3\n" +
    "kljvvxlvpctfz3seven\n" +
    "jkh8\n" +
    "9sixxvfnnznttseveneight5\n" +
    "92eight56onezpvrj\n" +
    "chzsx4\n" +
    "53fivetspsfive1fivenlmtvbl\n" +
    "plvcvn3brcrcqr94six5\n" +
    "cxqnlbplone97dgpjkkvfsksix64\n" +
    "eightlcsjrkxeight4qbgjffmnxlsvzcdsvbl\n" +
    "4ghbljhttp36\n" +
    "ninerpztrhv12\n" +
    "threeeightthreeoneeightsqdknqlf2tg\n" +
    "tbfnine8fourfivekllthreebsqjgqpvsm\n" +
    "6oneone\n" +
    "eightsix2seven\n" +
    "t8fourtl\n" +
    "6six76eight\n" +
    "ldfkqkgfiveninerqsrscftpv57oneightr\n" +
    "vcnfvftwo43\n" +
    "kggflclnzjjvxkc5\n" +
    "19five1twoone8four\n" +
    "77sixkzrpkxpzmgd\n" +
    "12fivemgxgbpz2seven\n" +
    "582gsvccszvk\n" +
    "fxtsdfrtbsgplxlqffivejtnsk9\n" +
    "kjhkjvz2dcxs2four\n" +
    "3twoseven886kr9\n" +
    "seven49\n" +
    "611mllnqfqlnvone4\n" +
    "18sixnpdcjcjpm\n" +
    "hvs9fivethree8gfdjffmfour\n" +
    "5two1threerkqxvsevenhmh\n" +
    "qpkdnine9fivehfiveseven\n" +
    "jkspcmqgv5\n" +
    "2vrbhsxmp74six2qcmnpsfffnthree\n" +
    "zqmdtrgktlvbjlsxjf7677jqt6\n" +
    "gxmtsevenddtpqpxhljoneninedjvhqhftcpb9\n" +
    "qqxxbhtfmpvdq4seven2jscgkqkj6\n" +
    "61365q\n" +
    "gvztklvxtwo8kmdlbzxglf\n" +
    "ninepxtd1pbcxbfhkvtsix\n" +
    "6cssbfstfbspvx\n" +
    "rdkhlqrhmj7fourbpbrqxmbxxsnthree8\n" +
    "12th3rlnqgpc\n" +
    "4szrvgbcbg6dpsjzcdvgone\n" +
    "lfour4\n" +
    "5threefour63qcvhpdxb7rmsdkl\n" +
    "4one452sevenfour53\n" +
    "nine5gfourfour5bttptfq9khknptfrbc\n" +
    "348fsvvfk\n" +
    "one6ttzlkfxc\n" +
    "sevenmksqtwocthdjtkhr95nine\n" +
    "7m3jlqrqb2six6\n" +
    "lrqqznf6nineone46\n" +
    "slpgjbslvtfgxsmbgzksevenfive4six\n" +
    "7jvnnqc2844qfzfour\n" +
    "64four353cpm\n" +
    "three9fivejlkxkzn\n" +
    "vcjbnpqj7plgbdblvgp\n" +
    "twofgqtzvspzjsxjkvrbs8fourgtfznpjxk2\n" +
    "seven44fppgfournqzmgfzfone6\n" +
    "h2jxdpkjktwo\n" +
    "kdkoneightjstgn9\n" +
    "7bbfsgl6sixdchgpnine3\n" +
    "nqvqmzxr86\n" +
    "3dpntnsdk\n" +
    "6ninefqblshpxvteightnbqzfszjndvzksfpsxone\n" +
    "59vztmq2three1\n" +
    "nine9sixhnfczn\n" +
    "pmkm3ctrbjrdninetwoneqzj\n" +
    "7znmpvqonecmmdcschn\n" +
    "5five5ninespthree\n" +
    "4xhmkgkmtgrtmrzrkjmgjsixninefxxxlvdknsix\n" +
    "7rnlfspthxjvlcs7nqtggmninefive8\n" +
    "5fourfour76gpseven\n" +
    "two9five45four3\n" +
    "5zhvmrbccf9fnsfvb3\n" +
    "3hcrhfkkthree\n" +
    "4xlgzlhjceightqxvsix83skhkkvzbtflbvvt\n" +
    "six58ppcxmph23lbxhvqmnnxheightwoklg\n" +
    "ninerbxxxtl4\n" +
    "4dvdjjfmhlfnzjrd3ninelrlhdpngvfdvdkjkbrone7\n" +
    "vpqtgkkdgqklmbc9three\n" +
    "foureight21\n" +
    "71\n" +
    "7two3kcvvfv\n" +
    "58vtsnlfkbt8czjb\n" +
    "6threebmncseven8nx8\n" +
    "eightmgsvctqb6xslnsgl\n" +
    "32sevensixmsppjkzrgqtmzvpsrljqssk\n" +
    "85l94\n" +
    "nzjqttsevenmrfzzv7\n" +
    "threetwosctspxzjgn5fivefour\n" +
    "2six8one87ppfhpqks\n" +
    "eightzfjfccdcvfiveone84jf\n" +
    "eight81eightsix5\n" +
    "foursrkldsthree5fzzmseven\n" +
    "7five3threet48\n" +
    "4twonelc\n" +
    "8eight6t6\n" +
    "qfheightwo43three785\n" +
    "two8cnsjshfpff4threeffqk\n" +
    "4dxfmd46\n" +
    "7grtxmvhcl849two\n" +
    "five4fivefive7\n" +
    "14ffour\n" +
    "92nzsk\n" +
    "13xmgqq9eightnptsixpvpntzcjn\n" +
    "29eightkpqnfour1jnine\n" +
    "4bcftnzdmcgvrczhzsn8dlqkzngjc\n" +
    "1pqmkbthtwo7\n" +
    "kzcsixxcsqmczrkjvhv3ppt44\n" +
    "eightfbvplm677csfzfncptflmgtrntqcpptj\n" +
    "fiveeightthreethreelvp1\n" +
    "dlvdhtvqvfctfl8four6vvrkgqddd6\n" +
    "msgtg12mgqcfvgxlgdeightthree\n" +
    "qzjkz5196fivevxkpvngfxrfourthree\n" +
    "seven4nineeightjsevenngfourfzdx\n" +
    "9fourjbone7kmsc\n" +
    "eight43nbklgg\n" +
    "ss4c\n" +
    "4eightsixglkqpjtwojhxmh\n" +
    "sevenfzrqv9mvkxgpghtc3one\n" +
    "fk7fsgndcrthree\n" +
    "7194czfive65\n" +
    "9nineone\n" +
    "six5djzqbcdncfour7\n" +
    "zceight3two4vfbmtfbh84bhrpbndm\n" +
    "7trqzbdjqeight4sevengzzsixjfkf\n" +
    "two3twovtzghbdcmc2\n" +
    "ninehrrdr1\n" +
    "3nvdvvjhxptsix7nlbdlz2\n" +
    "zdbsxpvbkfivegsndfourjftnlb43four\n" +
    "smgqrnbzd3plmsngdvz\n" +
    "lplz67\n" +
    "2pvqcpl2\n" +
    "mvhqninetwo2\n" +
    "1czljdtxnz\n" +
    "threefqqs696fivexssmqvpp\n" +
    "xtggzdrg4jllfkxtvv4xqlvtgrllseven\n" +
    "ncdxmjcfllr3eight7\n" +
    "3ftjjnzthreefmjmshdd\n" +
    "7jxs753four4\n" +
    "8eight54six2lxfnmtndgk\n" +
    "54sevenjnlnlc4zvmdd71\n" +
    "threebxcjdpprthree3qnsfqgbcsix9cbhlnvjdc\n" +
    "ptvdrm5vzc\n" +
    "8twolsxsgmzfqfivefourqlcpzggfm\n" +
    "skjzfblgsl4five\n" +
    "onesix9eight6\n" +
    "cnmjmkzmml732\n" +
    "l5one\n" +
    "fivesixclsxflmtml1nine3bj9\n" +
    "5zqbxz56lnbrntwo366\n" +
    "89seven\n" +
    "eightqpvztnrxxc4\n" +
    "svbxfssmfsnflkbzmqfsixdzfdlgeight31threeseven\n" +
    "tkkb2twofourvxcs4kgsvgkztjmseven\n" +
    "25qcjkptgbz\n" +
    "twokjcthrmnsrtrkhxptwo2ncrfive\n" +
    "seven92three1hnlbhzrghxone\n" +
    "onemvghbhpzxdhsssbms3sixnine99\n" +
    "qgtwone3sevenmkfourxqvvfive\n" +
    "lq141\n" +
    "gpvtdflfive852four\n" +
    "gdtwonekpfhtmkfseven6rqonesixtgdxttnjzc\n" +
    "seven2five6seven\n" +
    "skdxqonefourgrp6\n" +
    "djlninetwo7five23\n" +
    "hpxqlmqeight2\n" +
    "8sixeight29ninehfnllkvgeightwomp\n" +
    "326kvfsnb\n" +
    "eightfivetwosixjhjkhjtdpx4\n" +
    "mtdj4threemtqldccqhffive7pgnrcqpfive\n" +
    "seven74grtdbl29four\n" +
    "twonseven6\n" +
    "sevengmtlhxgqcbrjlhgzs3sevenkrfl\n" +
    "28zmfvgql\n" +
    "geightwolnnmmhczzj1p\n" +
    "hkbknzsbgpfourdfrfdxpqlz2seveneightseven3\n" +
    "34bbrjvdqszqgbkndxsz5four88\n" +
    "dxfhkfeight8qsix4five\n" +
    "xsnfslsc5one4dnrsxlrklt23zhgknhjrd\n" +
    "dgkrffzctzpk9fourdvmgnbbnfbt3\n" +
    "jbfkcm5sevensixpkfnqqgffdvkgmjsbpkpqvsixjrvm\n" +
    "mckpzdvnlrsltktbgeightjk6xvsfmhszr\n" +
    "1one46three\n" +
    "77eighthgzqqg1\n" +
    "threechgthtshpqnxsixmzqqxbzdtwoeight1five\n" +
    "ltnkv3186eight5five\n" +
    "fourncknkmdvfpgtdkqlxone5nine8\n" +
    "gvnvsxrfdcfivekfcn9threebsxdsnbhtwo5\n" +
    "89nnprfkrhrmfdzqssdjspvzzpshnzxsrzctwo\n" +
    "3sevenxhnlcgkjnccgbrnfhzc\n" +
    "678fivedvtdchqsevenqrmvjqlq5sfxnqj\n" +
    "xbb3\n" +
    "3d\n" +
    "81sevensix\n" +
    "59sixg\n" +
    "3foursevenone\n" +
    "four6nine48\n" +
    "6lkhqsixnnhsjqeightc96\n" +
    "sixfiveeightthree9nnvsgmgllbqvgjpqhfqtznm\n" +
    "sqgxfourninenqpgx15fiverpk2\n" +
    "zlr8fthree\n" +
    "jnztj59\n" +
    "5eight13fourjvxfndzptfnjpqzlb\n" +
    "459zpnrzbxdsplpspnh9zbqvdnxgdfour2oneightmfd\n" +
    "28twoddhpqzf7\n" +
    "6nine2168mcgnmc\n" +
    "4fiveqvmd8157\n" +
    "1sevennine8793kxkx2\n" +
    "sixrbr6ninemdmsmjrchbvhvpmmsfphtslll3\n" +
    "one2qcrqhbqnine\n" +
    "rmrbtgfkd2cbzpggbp6\n" +
    "797fbxjbb\n" +
    "fiveonevsv2four28\n" +
    "six9sevensix\n" +
    "7nxztt\n" +
    "three3vcqrjgjndsbxpvclvg2vsv3\n" +
    "22rgm3\n" +
    "jxrgtsdzppone5twoj1sixmrdxrsbmf\n" +
    "44fivefzkdrvrdp3hbmp\n" +
    "17bgrjbxone5vvnztxhpztnmvtworzmc\n" +
    "keightwoonethreefourtx4six\n" +
    "2threexlsn\n" +
    "8ktqbzfninexpgkppg8\n" +
    "295hcbbnineone7qdgcvjzcs\n" +
    "hjshndvhgz3bjh4sixeighthvxmdtkkbgqbsdxg\n" +
    "8jdnprbkmxttwo\n" +
    "fivetxhgnjfkhlxgts2pqrvjbscrq8vqtbmkrpxlkhvkff\n" +
    "njgkqbnkmdqjqldmpdfc1mjqvm2eightxzlbcz\n" +
    "2ljrbbmseven\n" +
    "xmxqpchds889fourpnzfdljvfltwo\n" +
    "six4jvfnfsfjseven37\n" +
    "ddbgmgseven3ninefourmtlvkxbrnvnjdfspjffour\n" +
    "5mkjjnine6one\n" +
    "7fournqg9xvpfh\n" +
    "sevenfourone659gqddprfrqg4three\n" +
    "twothreem382\n" +
    "onetwoeight8kqbtmbdhc\n" +
    "817onefour\n" +
    "8gmxjzj\n" +
    "bckmc3four3three\n" +
    "746cfhl4nffcksqlonefive1\n" +
    "five338\n" +
    "five4bzkg\n" +
    "thltwonefour9nxznrcfbx52onem\n" +
    "four5bzbhzvmqqbhkone2three\n" +
    "seven4five85sixcf\n" +
    "4drchjthree4\n" +
    "sevenzsg9vmdjcgsvvxz32fiveseven\n" +
    "hjnkgzchqfjfnfv3dxbxn4\n" +
    "76sxzjqfhpc44\n" +
    "72threesevenknkbdhqvkpcxvhlldhzdkone\n" +
    "six4srtzrmgksrvkjktchl\n" +
    "sixvnhlzfivelppsevengbndbprhn4\n" +
    "five1sevenstpfjpbg4\n" +
    "3ztrhnxkpmh\n" +
    "czpbffqlkkjdfmkspxvfrqrgn4rfmzvfive\n" +
    "fourthreethree1nine5ninekgqxlhvtlr\n" +
    "4tcjctphneightptlqlvxmfkb5\n" +
    "cvbv798pzrzmfivesixqhxdntdtcq\n" +
    "6jkqptcvrjdnqtkblfour4ninedv9two\n" +
    "four51eight\n" +
    "3two9eightlbvdcrxkfive\n" +
    "3six5three\n" +
    "3threesix65seven\n" +
    "3three8two\n" +
    "45b9sevennqnmkmps\n" +
    "7threefourseven7cmtmnfive\n" +
    "6six8seven4four66\n" +
    "sevenfour91sc6sixghqhfmgcfour\n" +
    "ninelmcxtwo4hlstzlf6\n" +
    "six45fiveone\n" +
    "seven9sevenqx3vtk\n" +
    "skpsxhnqsix3one\n" +
    "vzveightwo5five2sevensevensix\n" +
    "cd9nine23ngrcmcxtd3ltpcn9\n" +
    "vcnfshkpone72ldgtqonehjq\n" +
    "cgqvcjnbtwohkmcfsvfr82nine9\n" +
    "8one75fouronedklf\n" +
    "3fivenvnhlrthree\n" +
    "369sevennine9twofour2\n" +
    "ninevpbmftmll57fivedjqpxnpcjfour79\n" +
    "71rcpfnl5\n" +
    "psixzxslfrmxdkcxvthree61npplpmrmnkjnvloneightfl\n" +
    "42six3fournxkjcdslp5ninetwo\n" +
    "8frbrhghpggq2zxjhrqdssixfivefivejrbd\n" +
    "foureight1pgsbkhkjnz78seven66\n" +
    "sevenfive4ngxfivezs4fcvx\n" +
    "kxjjbcxx6qh5jpzkgml\n" +
    "7gmgqrxt9fourk78hmmjt\n" +
    "nineseventthxmrxdsn91three\n" +
    "seven1mbqn8fivezpnrpjbpsx22\n" +
    "2hfvqkeightrnscdeightglb\n" +
    "onefive7\n" +
    "heightthree4qdnvhxbzjpd7vvseven\n" +
    "ninengrzsztmtnkjmjmzqqqpcbx7fourtwoeight6\n" +
    "sixfbrj7two83\n" +
    "eight1vnqrf9zdnineninecbfcj4\n" +
    "chsldbpnmxlgbjqbpkh34six5prb\n" +
    "zrjjtlnc66271dssfour\n" +
    "3zsdjzpqtwonec\n" +
    "eightclmbz3gphlxeightwov\n" +
    "5cgvfive\n" +
    "fivenine54five9\n" +
    "64ninenine1371\n" +
    "rvxxeight5rmd8three\n" +
    "3fivenfhskrlzcrcdxjvsmmxfiveone\n" +
    "sixpmpx7jbdone7qldr2hz\n" +
    "3two8nineone9\n" +
    "6sqdqv\n" +
    "pflddeightonensqrchsrsixseven2\n" +
    "threesix2sixsix2\n" +
    "5594zhlqbkfmmplvcclxjcgngmfrbsrxbfn\n" +
    "fourblpmgmtxltjdmrlmdfourf7bdjllqsbh\n" +
    "4twooneightf\n" +
    "fourjvddcqsxbcrjthvcjjshbngkrfive4\n" +
    "threethreefbdvxfksrsfnrk42hptbr\n" +
    "692nrjhjfpgg4foursevenlgm\n" +
    "fmfbd6pcqff93\n" +
    "gcdgfourbtttvlone21three\n" +
    "onejczqmpbrjqmljmchkmh77mnzsxp\n" +
    "cnpfc87three\n" +
    "2one4\n" +
    "hzdpmxflk1581three29\n" +
    "97tnzqknz15bxttzrsix\n" +
    "5eightfive\n" +
    "894six675\n" +
    "fourcqmgpdsjdjcvmgtsevenndfkgrnqbp6fourfive1\n" +
    "fkhfz1kthreethreejndpdrjddnvztgt\n" +
    "tpn3threemxtdkfphvctwohklcbzdn74nhhfjr\n" +
    "5fourfour\n" +
    "six8twoeight163mrkvvc\n" +
    "ninersix8\n" +
    "1twofivesixkbpljt\n" +
    "67nine11tdnplxklxkdbxffn6\n" +
    "ninesix9gfive7jvvmcrnine\n" +
    "2bvsqxbd7drclkbxrtnine\n" +
    "gtrmtlzzsixjxqhzxcdqppmf45two\n" +
    "three43threefdmsjxxdvkthree58tblfvxx\n" +
    "one1365sevenjzbgtrjtlc\n" +
    "1twosevensixnine4four2\n" +
    "1fourfzone7\n" +
    "cpzjzkjzkksfzv96zxfzhfzsvslbmqdshdthree\n" +
    "191kbfcfhtmgbrnfv26chh\n" +
    "vfcqrcrseven3\n" +
    "nine51\n" +
    "twosbtkk21\n" +
    "8twopvmrkntqlzcth9twozxrfvgmfjtqtt\n" +
    "sn286four1tv\n" +
    "xqzgxhlzjh9vnjvjcj\n" +
    "three24lkqphqnxmt996mhcqhpzksn2\n" +
    "4vpngckh\n" +
    "seven3v3r1eight\n" +
    "one9kxg\n" +
    "twofour4fourjcqjznsv\n" +
    "mnine5foureight\n" +
    "fourchqtjtqonesevenmb319\n" +
    "17sixqxxgnine4\n" +
    "1srrc7\n" +
    "8mzhtnhmshfourthree1vonet\n" +
    "qzppxshxfninesixk13\n" +
    "9sgbnnspt4seven2248\n" +
    "seventwo6\n" +
    "687541rsk\n" +
    "ninenineeightmgpn71five7five\n" +
    "eight9twonineseven4eight\n" +
    "ninesixnszfprlcftgcpcxdfhxs5eight\n" +
    "xxthree7n\n" +
    "tworxtcqscbc6243zhcd\n" +
    "two636nzhpbslxhrlkxb\n" +
    "six7nine\n" +
    "78five6one\n" +
    "98twokpxjvkjbxxfourlfnnttgqzh\n" +
    "7sevendzghjfczcmc26tkshcfhrhhzxone\n" +
    "fivethreethreenhfrtdtg7ninetv2fggncj\n" +
    "prsptrgmtbkxvrpsix39mqqbnqf4\n" +
    "bctcqqqjtp2jshldz\n" +
    "ninetffzllkztqvtm9nsbfkbbfteightsixnine\n" +
    "jvvcsrd1657nine\n" +
    "8cbltrdfzdeight8lv3q\n" +
    "lnine3ninenine8pczjsj\n" +
    "88ngpzzzvzrhqxvzcdrrln3nine\n" +
    "qtrbmdqgnggmjqxbx8nine1sixfive\n" +
    "477\n" +
    "tckszrqktzrbc3one5\n" +
    "seven5seven8mfzfzvrm2sixone\n" +
    "zl29fourone\n" +
    "lzctr93bmrgsixppljzgzrvh8\n" +
    "fivegqcx4fourninefour\n" +
    "6tmjrtfive6nine7xoneightgxv\n" +
    "9f\n" +
    "r4fstldg\n" +
    "twoseven7vjjfgxvq\n" +
    "dkpxkqnq9\n" +
    "kninefournineseven5twolldkfrcjk\n" +
    "2kfbdbfqvkqvtjleightsix\n" +
    "nine7gn3rphbnllpq\n" +
    "five12\n" +
    "ngpzsjttwoninefpgt549\n" +
    "2mdqsrrxnhn\n" +
    "twotmgtbxqhx2dzzjlxlc3gdrt4\n" +
    "7sixldnkf2four2bxjv\n" +
    "3nxdsdnschqpjgsbghtl65mmbsxklqr9eighttwo\n" +
    "doneight542nsglfmbrpzcgx2xsixnine\n" +
    "7ndhvcpcbncseven1\n" +
    "dxxzmpdbq33five\n" +
    "xhrfpsgdh3fourgpt1sslfnt5\n" +
    "dlddczbzqchdfhlnnrqcdn5\n" +
    "5eightthreegbqgpgsevenfourxjvzthree\n" +
    "4rtplhnine\n" +
    "twotwoonenine3\n" +
    "six2eightsp6\n" +
    "mtsixtwofour8vdfr7bndr\n" +
    "grrtbdjtrcfvnine7\n" +
    "jtzhfqsvxthree6dqcjgmj\n" +
    "83seventhmvgvdrx7\n" +
    "957six7crlxqfdbxnjhpxkstktspl\n" +
    "twoeightfivekmfdrttbbtwo4kzcxksbs1xsnm\n" +
    "8eighteightfoursixsix\n" +
    "eight1nine\n" +
    "3xdtdbq\n" +
    "fivepthkrnlls63pl1qhf\n" +
    "674fszvbrtskfmzs\n" +
    "jdghpqtwosix52hggmrlkhqsevenbnfdckqgr\n" +
    "9two89bvckm7sevenzkdfclktgc5\n" +
    "twosixnvqfgcht9656three\n" +
    "vsktxrbjgt4zxffxftwoeight21four\n" +
    "twofiveznfzntzteight838cppl\n" +
    "18three57fourseven\n" +
    "rnxbcmszgbeight5\n" +
    "twozpmknt3threecjzbcvtwo97dqzkmh\n" +
    "2fournine\n" +
    "tvngfkzgj6sixgbspfpbgzmrhlb7\n" +
    "162fivehtvcpsgmxz\n" +
    "695dcktwo\n" +
    "fiveseven5jzlcvxctcf\n" +
    "3klrsxtgbjttwo\n" +
    "seven17hkhpbdtonevhkgvhrzxbsix\n" +
    "3twos\n" +
    "cssixsix956xggjfzs\n" +
    "threetsrrchdt62cmzqzvzh\n" +
    "onefour3\n" +
    "sixzxbbplldcz5dgtrm196three\n" +
    "2onejstvfszgtwodclflrrdvr\n" +
    "9zgkcffscqfhxvlm7sbtlckone\n" +
    "xvnjnvctnpskzzxfl511jfkhtkxmjcdjxdxvrnzs\n" +
    "eight73mfsevenjjneight\n" +
    "ninehfqxjhsmr6foureightqptrfcvst57trlvnkfh\n" +
    "ct562pddspdjseven\n" +
    "hxcslbmf9453\n" +
    "seven9f2bcftjdb4hfxl\n" +
    "eight397qjkqvthree5dxqnrk\n" +
    "nnhdtvpvk1two\n" +
    "lp432sevenone56\n" +
    "mh3sixxdnpthreesix\n" +
    "nine9oneightgl\n" +
    "ktdfxvzsvhlr85tthree4\n" +
    "onenine5three\n" +
    "lggrspnkktfoureightsix9hvtgcrltthnkjk\n" +
    "1g\n" +
    "frbphfseven1rhrhxfdzctdqkctjpjknqr8\n" +
    "fourfourone2seven\n" +
    "fivefivegknxfmggnplhfhbpjvlnpxlzoneone4\n" +
    "gzqthree6ldltpkv5krjnslbxsmrvqqvgkpg\n" +
    "ninevrone66\n" +
    "tjsxlzd995sevendoneoneeightwod\n" +
    "threenstfpninetwo2\n" +
    "2827hsdrnndt\n" +
    "zeightwotjnftwoonebzsnkghseven2\n" +
    "7twoneightfourseven\n" +
    "6kdqzbngsg6eight\n" +
    "hxvvvrtqkvbmprqjvvsevenone9\n" +
    "fourfour2ninetrhcqs\n" +
    "sixvzbd53\n" +
    "mkqpshhbxnsfbfiveeighttwonvxkm4\n" +
    "two6pnnzxhm8kpdkhntlpqzfqlfnp\n" +
    "fourhgzrsplfcmjflrf174\n" +
    "fivefkxrdrfcr4\n" +
    "pqgmrvltcgphhcz55\n" +
    "ccrqsztx6cpxsdvjsnsevennhtxbkm\n" +
    "27twopnschsix79\n" +
    "9kvonekrjkcxlrhvgxh\n" +
    "7rdmxdvb34fivevn69mnhhnmtbmn\n" +
    "vdvttfcfdqgzpninetxbtrjkfbmninetwo9z\n" +
    "four2three\n" +
    "67vjzfsevenfivefour6rnqlv\n" +
    "jhqkmhpnv7\n" +
    "sblrrklj9twofivevqmhgjrvqjzvxqqrxqnch\n" +
    "5mqgbgjbztvhsixpsmmtqr\n" +
    "kqkpd5eightrhzmsnbsn2bpflnhtflp\n" +
    "dtwonerpnzkztksvrnrjktpdnstwo9hzqlsd\n" +
    "xqlsxtfshhgqtzzsfsdnknkfv4fiveone\n" +
    "fourfive64\n" +
    "tprjnvfeight8jf\n" +
    "ltvghtsvrttnhcvkldvttrpjfxrsfkscnine8ltrbclsjfour\n" +
    "8eight2jqrscqbkcxcone9\n" +
    "57mrgvrsrjkttwo26hrhlcckgcjqppczf\n" +
    "84scltxqgqlpxxxchmsevenlhjgreightwozs\n" +
    "xhdhbqzzctwoxpqrvtwovtrmtwombvgjmtb1\n" +
    "ninelr5\n" +
    "heightwo2\n" +
    "onevbjvninelsxlbgjqmtwojc6ksx2\n" +
    "dqsblgrckb6dgzhkkeightoneeight5\n" +
    "2lmrlthreefive6\n" +
    "9rgdspmxqj4ddzbn\n" +
    "ninehgbsixpmgjq7pddxzbvh\n" +
    "pnbvrppdh8\n" +
    "xfpnbsjjnfl7lnm\n" +
    "cldxp9qs\n" +
    "cmnoneightgkx9eight\n" +
    "1fbdf5two\n" +
    "six3eight4\n" +
    "8three2h2\n" +
    "6eightzjzhdnffnrrkbnvjlpn9seven\n" +
    "7dxt\n" +
    "dgqhqxnhgmdn9one\n" +
    "4fourfourbmv9gplqbjgqjdsixsdfsmrdh\n" +
    "8ninevqzzkgctwo4three\n" +
    "kkvkfivefive197qeight\n" +
    "djblkcrp5btpnbbvbggclpmbfbp5hz\n" +
    "nine59\n" +
    "5onex\n" +
    "98f71ngphthree\n" +
    "gs72xdvbn639\n" +
    "nxdqfour11six8\n" +
    "9dzjtskgmztkgzqsfvkljfeight\n" +
    "bddtwosixtwo4two1\n" +
    "5ninehqmqcfiveqlkszqpsnf\n" +
    "qjnfour84hlzgk9\n" +
    "8one13twofivelgdlzxtwo4\n" +
    "sixnrsnxdpqseven3onefour\n" +
    "tnine15nine9\n" +
    "1sixsevenzxzssq3five\n" +
    "vgmplmbqp6\n" +
    "474dkjqxponehrtzhcdkpjsixrfrhgsmpmcdj\n" +
    "one7vpjbptdczcjone9threekrnrvhsjseven\n" +
    "vtrdvvhr4one8lmp8five\n" +
    "seven7tjxbfourpnk7eight\n" +
    "two8fivefour3dcpfkvqqk3\n" +
    "onefivecm7seven7nxtdbxgv\n" +
    "2tbrjrxkcdxeight7lbqprjkv\n" +
    "nine9clgppmjqbczxgpm4qjcktms\n" +
    "ffqdvccvslnine4mpznnjkxp219seven\n" +
    "tworcpjshxfnf23vdvp7rzjfhlgtlf5\n" +
    "xc22fivecpxjlskm\n" +
    "8jbrzjroneninethreefivevhpp\n" +
    "lvvcxptngphhgfbvj25eight6sevenfive\n" +
    "52fpkhmsnfivesevenfivefiveksxlnznzsngs\n" +
    "threeonefourseventhree92hrmtkprxzrrmrhc\n" +
    "kjqph5mkhglseven1four\n" +
    "rqninehxvvslkzl62foursixxlbjnfhgnmzls\n" +
    "hj2eightpninefour3\n" +
    "8nine1\n" +
    "9eight12hlsbhtsshzrthreevzkpcnhkbg\n" +
    "twosevensevensevensixbtvdcdbhkqjlnrvn8eight\n" +
    "pjpzmzqgbthree3\n" +
    "7xpdxjpq71seven1one\n" +
    "7chszctznine1\n" +
    "gprhvmvp4\n" +
    "twoone8ninetxmhfhzveighteightthree\n" +
    "eightgccstrqxjh7\n" +
    "qcnbcfdhnine3qfbsxbsnhf\n" +
    "mmsfvcxb6fivesh\n" +
    "7mzzppcfblnrxkk\n" +
    "fourfournine6five77\n" +
    "zrpkzfivegkfsxcsptjvsgvdsjfgvrn83one\n" +
    "fourninetwo5nzp9\n" +
    "vpteightwo2eight7vxvlblvnnskqzdtp\n" +
    "sevenbfdjs36zr9791\n" +
    "ceightwo8nfzkthree\n" +
    "twocnjmjxznine9three2\n" +
    "seven4qxznjddnvfivesttbbgr5six\n" +
    "46fourvlgnzfzt\n" +
    "psxcxreightkqggjj823sevenlhvh1\n" +
    "ninethreeeight9\n" +
    "2glvrxgflhjbsfivefeightljtdg\n" +
    "fivenine4\n" +
    "52hgone\n" +
    "33fhspjthreesspqfnone\n" +
    "srkzqmnqgr1\n" +
    "gtxxbfndlssbntrnspdptjkbdxgpxgd9nlddsndjzmq\n" +
    "zjxvbmjbqjkdgdghplk536seven\n" +
    "sjdgghzkrr4rvvfx2\n" +
    "4eighthxxdksdtr\n" +
    "5two9xlrbndb8\n" +
    "7twoonedhdtkqj8pgcsvjmzm\n" +
    "76threenine2vjrcmbf2six\n" +
    "sixtnrf3nine\n" +
    "nine3onebptlmfxzhppmsprg88\n" +
    "sdvmxlccfjqrdzjtxgsfour5bt\n" +
    "sixsix53f33\n" +
    "eightonethreezrrlslcvsm92eight\n" +
    "9xfs162pmvbzzkjjksvqpcqlcdtjdrt\n" +
    "four93sevennine3\n" +
    "sjmoneight5349\n" +
    "scdjfs2ninesevensixnine\n" +
    "four38rtkvp78dbggkmbfhzeight\n" +
    "seven56trjmqvk5three2\n" +
    "qlnbmvpmdspthree5bmcz\n" +
    "sixxsdb6lkbrhthreesntwo\n" +
    "five24\n" +
    "eight6sgbmspbj5qrzconempkp\n" +
    "7nnzmtn1sixpplhjblfmknn\n" +
    "67seven629\n" +
    "8fourfouroneightr\n" +
    "73hq186onecmlp\n" +
    "sqxcqvlsmqj12\n" +
    "vsdztxsm837twohszjzcnghvng\n" +
    "6lmkngcrthreefourfivefourcfbkzlbkxlmcdzvg\n" +
    "onesdmsixpqdgxhhpkqxts2\n" +
    "threexcfjj6\n" +
    "tvgsxk6\n" +
    "jnhtlnbr1oneoneonefpkkvpmj\n" +
    "jdftkkjmqbtxcfpstfxseven5three\n" +
    "12twocjlqvcqthhndseventhreefive\n" +
    "fivesix7four3\n" +
    "7rshgk6ninevlkrt6pjfvrspvljfkf\n" +
    "bxjnbmgvnpsxjxqz7vkjztwo79seven\n" +
    "threetwo46two9bxrjsbzm\n" +
    "5twozhqnbx514eight19\n" +
    "oneseven2nine7nine1eight4\n" +
    "five9threekpstk\n" +
    "2five3cxlrbtfivethree\n" +
    "ljrhhfhgj3fiveeight571\n" +
    "65threejpr2two25\n" +
    "3five1threekznxssgt84\n" +
    "698458\n" +
    "194f\n" +
    "hxxpzlqtkninethree89fivejdthree5\n" +
    "frhzzhggn2qnxqklrtrvvdhvnhfkml\n" +
    "4lch748threeeight3\n" +
    "six919mkvqrbsnreight3one\n" +
    "three7five7seven\n" +
    "threetwo3\n" +
    "67five\n" +
    "sixft9\n" +
    "nineqrh4\n" +
    "mvtwone57hone3xntlkbktdcfxjhm2fsckqbcbqx\n" +
    "nhzhqmvvkgfourbnzrfnm5sixfivedmfqldqqzptwo\n" +
    "7xvmvpddlv43hkvgprfour28\n" +
    "brlblxt2\n" +
    "qqxtd9seven\n" +
    "sevenoneeightsixrxvhnx9g\n" +
    "5tjpxkgtqxn3ltnht6\n" +
    "sgnfscdnd52twozg\n" +
    "fivetwo5three5nine3fourtqdfnzgn\n" +
    "66mglqh5vsbqtthdbtxpztnskf1fv\n" +
    "xlleightwo72tctrvxfk4one\n" +
    "8fivedrsmv1mrcszrkjfscjztwo1\n" +
    "4eight92twolpbdfivecbdnjzs\n" +
    "pgfftmjxqzrc7sjvssvbx1ldkjp\n" +
    "ldvjjqgjhd9four9eightpgddrrc62\n" +
    "9fourfourkqgdf\n" +
    "five4eight9xmkzbqvtgthree7chfjlpc3\n" +
    "12bllmj36\n" +
    "mjqhmqnbhjtbxkrsrppeight2dctpspsix58\n" +
    "twoqblpscffvrflclttck7\n" +
    "21twosevenvpkzpmq\n" +
    "gvmtwonineseven6\n" +
    "twog26sixnhgnqmlninetwo\n" +
    "fivefiven1mqxsevenvqbkfqsrtmghfxtpsrrd8\n" +
    "five8oneeightsixtwocfcdgmrdsstwo\n" +
    "vlxxnmnineqxnsixtwogq5\n" +
    "2eightwos\n" +
    "hs4qttkxpggjtxdbzfvcd8onervnfh\n" +
    "lmc9\n" +
    "4nine1fxmkcvllvfivevqcvflgnqntwo\n" +
    "73cpgmckj\n" +
    "four7four92lfqkmgponeightbf\n" +
    "eight4fseven\n" +
    "two3sixfivebdmfkhbngrpj7nfrmj\n" +
    "745twovchzs3rgctnrqgt3chslcd\n" +
    "bgrhrgjbrtqshcg69sevensnbseven\n" +
    "six6sixzhf\n" +
    "9fourfourthree\n" +
    "9f93ngbbnxkpt1\n" +
    "fourfivesvpddkvmbchdjggrtwo7\n" +
    "7fourbvdtdrrxlsixkvsevenfstssflone9\n" +
    "eight2ninetwo\n" +
    "nxb9five3\n" +
    "one7xvtwokqnfxp\n" +
    "two777vrlcxfsmrcnine576\n" +
    "xxhmbpvr7vvppfreightthreefivefive\n" +
    "pcs3sxdgvtwo3\n" +
    "fivegpgsfjhcg1eight\n" +
    "nine8fzqgffnqrbdjsgxskcqxz75\n" +
    "tsvtwonerjmgtbzng9\n" +
    "6xssgdfxxssrfive\n" +
    "2seven42h967\n" +
    "63zzmdfcjtxtnineqjncktkkttjfrr\n" +
    "7eightfjphdvgs4nine\n" +
    "6dxbttshgcvfngclmhvbzfeightnine\n" +
    "1eightkgqtwo8twotwopss\n" +
    "46two\n" +
    "34t65six\n" +
    "vfh4zteightkvbpps4rxhlnctjztjfvdvdxfk\n" +
    "9zpdnq\n" +
    "4klxpvncr5\n" +
    "dsjmjbtvhv1fskzhvfrtc44\n" +
    "7two5\n" +
    "3lnksqznzh\n" +
    "five5four32two\n" +
    "llkbrncncr5nvsmbrzdnine6\n" +
    "nine57\n" +
    "7rdtplhbvddvlkonefqsttj\n" +
    "four6mssqzhgxt\n" +
    "gphnqxhlhzzftghk767\n" +
    "mbcbpjcsnt4six\n" +
    "one9xmhvzklmzffive1kcsixmnsbm2\n" +
    "1dgschj\n" +
    "nine8foursnczninednds\n" +
    "9sevensixrsrgmclkvthkgtxqtwovtlxfrdnllxvsghslh\n" +
    "seven443six8three31"

const stringToNumberMap = {
  one: 1,
  two: 2,
  three: 3,
  four: 4,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8,
  nine: 9,
}

function getCalibrationValue(input) {
  const inputArray = input.split('\n');

  let result = 0;

  inputArray.forEach((item) => {
    let firstNumber;
    let lastNumber;

    const filteredItem = item.matchAll(/(?=(one|two|three|four|five|six|seven|eight|nine))|\d+/g);

    for (const match of filteredItem) {
      if (!firstNumber) {
        firstNumber = Number(match[0][0]) || stringToNumberMap[match[1]];
        lastNumber = Number(match[0][match[0].length - 1]) || stringToNumberMap[match[1]];
      } else {
        lastNumber = Number(match[0][match[0].length - 1]) || stringToNumberMap[match[1]];
      }
    }

    result += Number(`${firstNumber}${lastNumber}`);
  })


  console.log(result);
}

getCalibrationValue(input);
